# Do NOT update manually; changes here will be overwritten by Copier
_commit: 03f1afd
_src_path: https://github.com/openspp-project/openspp-odoo-addons-repo-template.git
ci: GitHub
dependency_installation_mode: OCA
generate_requirements_txt: true
github_check_license: true
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: true
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: false
odoo_version: 15.0
org_name: OpenSPP.org
org_slug: openspp-project
rebel_module_groups: []
repo_description: OpenSPP enables the mass distribution of communications through
    SMS and Email, allowing the organization to engage in large-scale communication
    campaigns with beneficiaries.
repo_name: OpenSPP Communication
repo_slug: openspp-communication
repo_website: https://github.com/openspp-project/openspp-communication
travis_apt_packages: []
travis_apt_sources: []

